# frozen_string_literal: true

# rdoc
#   A tag set represents a set of tags that are displayed together.
#   This class makes it easy to fetch the categories for all the
#   tags in one call instead of fetching them sequentially.

class TagSetPresenter
  extend Memoist

  attr_reader :tag_names

  # @param [Array<String>] a list of tags to present. Tags will be presented in
  # the order given. The list should not contain duplicates. The list may
  # contain tags that do not exist in the tags table, such as metatags.
  # @param rng [#rand] the source of the credit phrase's roll (see
  #   .credit_phrase); tests pass a fixed one.
  def initialize(tag_names, rng: Random)
    @tag_names = tag_names
    @rng = rng
  end

  # the list of tags inside the tag box in the post edit form.
  def split_tag_list_text(category_list: TagCategory.categorized_list)
    category_list.map do |category|
      tags_for_category(category).map(&:name).join(" ")
    end.compact_blank.join(" \n")
  end

  # Fork: the credit before the artist names, drawn per render (operator,
  # 2026-10-08). Upstream says "drawn by"; most of what this booru holds was
  # not drawn. "created by" 94 times in 100, each of the others once. Weights
  # are whole numbers summing to 100 so a roll of rand(100) picks exactly one.
  CREDIT_PHRASES = [
    ["created by", 94],
    ["generated by", 1],
    ["genned by", 1],
    ["willed into existence by", 1],
    ["hallucinated by", 1],
    ["requested politely from a robot by", 1],
    ["the output from twenty five gallons of water boiled by", 1],
  ].freeze

  # @param rng [#rand] the source of the roll; tests pass a fixed one.
  def self.credit_phrase(rng = Random)
    roll = rng.rand(100)
    CREDIT_PHRASES.each do |phrase, weight|
      return phrase if roll < weight
      roll -= weight
    end
    CREDIT_PHRASES.first.first
  end

  # Memoized per presenter, so one render's page title and saved-file name
  # carry the same phrase.
  def humanized_essential_tag_string
    chartags = tags_for_category("character").uniq(&:unqualified_name)
    characters = chartags.max_by(5, &:post_count).map(&:unqualified_name)
    characters += ["#{chartags.size - 5} more"] if chartags.size > 5
    characters = characters.to_sentence

    copytags = tags_for_category("copyright").uniq(&:unqualified_name)
    copyrights = copytags.max_by(1, &:post_count).map(&:unqualified_name)
    copyrights += ["#{copytags.size - 1} more"] if copytags.size > 1
    copyrights = copyrights.to_sentence
    copyrights = "(#{copyrights})" if characters.present? && copyrights.present?

    artists = tags_for_category("artist").map(&:name).to_sentence
    artists = "#{TagSetPresenter.credit_phrase(@rng)} #{artists}" if artists.present?

    "#{characters} #{copyrights} #{artists}".gsub(/\s+/, " ").strip
  end

  private

  def tags
    Tag.where(name: tag_names)
  end

  def tags_by_category
    ordered_tags.group_by(&:category)
  end

  def tags_for_category(category_name)
    category = TagCategory.mapping[category_name.downcase]
    tags_by_category[category] || []
  end

  def ordered_tags
    names_to_tags = tags.index_by(&:name)

    tag_names.map do |name|
      names_to_tags[name] || Tag.new(name: name).freeze
    end
  end

  memoize :tags, :tags_by_category, :ordered_tags, :humanized_essential_tag_string
end
